gui:
  authorColors:
    "Harrison": "#df8e1d"
    "Harrison Cook": "#179299"
    "*": "#e64553"
  theme:
    lightTheme: false
    activeBorderColor:
      - "#40a02b" # Green
      - bold
    searchingActiveBorderColor:
      - "#04a5e5" #Sky
      - bold
    inactiveBorderColor:
      - "#4c4f69" # Text
    optionsTextColor:
      - "#1e66f5" # Blue
    selectedLineBgColor:
      - "#ccd0da" # Surface0
    selectedRangeBgColor:
      - "#ccd0da" # Surface0
    cherryPickedCommitBgColor:
      - "#179299" # Teal
    cherryPickedCommitFgColor:
      - "#1e66f5" # Blue
    unstagedChangesColor:
      - "#d20f39" # Red
    defaultFgColor:
      - "#4c4f69"
